irrelevant_hearings = ["House Natural Resources", 
                           "House Natural Resources Subcommittee on Water, Wildlife and Fisheries", 
                           "House Natural Resources Subcommittee on Energy and Mineral Resources", 
                           "House Natural Resources Subcommittee on Federal Lands",
                           "House Natural Resources Subcommittee on Water, Wildlife and Fisheries",
                           "House Indian and Insular Affairs",
                           "House Public Lands Committee",
                            "House Agriculture",
                           "House Agriculture Subcommittee on General Farm Commodities, Risk Management, and Credit",
                           "House Natural Resources Subcommittee on Water, Wildlife and Fisheries", 
                            "Senate Indian Affairs (Select) Committee", 
                            "Senate Agriculture Committee", 
                            "Senate Agriculture, Nutrition, and Forestry",
                           "Senate Agriculture Subcommittee on Commodities, Derivatives, Risk Management, and Trade",
                           "Senate Agriculture Subcommittee on Conservation, Forestry, Natural Resources, and Biotechnology",
                           "Senate Agriculture Subcommittee on Livestock, Dairy, Poultry, and Food Safety",
                           "Senate Agriculture Subcommittee on Rural Development, Energy, and Credit",
                           "Senate Food and Nutrition, Specialty Crops, Organics, and Research",
                           "Senate Energy and Natural Resources",
                            "Senate Energy and Natural Resources Subcommittee on Energy",
                            "Senate Energy and Natural Resources Subcommittee on National Parks",
                            "Senate Energy and Natural Resources Subcommittee on Public Lands, Forests, and Mining",
                            "House Natural Resources Subcommittee on Water and Power",
                           "Senate Environment and Public Works", 
                           "Senate Environment and Public Works Subcommittee on Fisheries, Water, and Wildlife", 
                           "Senate Environment and Public Works Subcommittee on Clean Air, Climate, and Nuclear Innovation and Safety",
                           "Senate Environment and Public Works Subcommittee on Chemical Safety, Waste Management, Environmental Justice, and Regulatory Oversight",
                           "Senate Environment and Public Works Subcommittee on Transportation and Infrastructure"]